### ISSUE TITLE
Add retry capability with back off and eliminate auto-shutdown

### ISSUE THREAD

**Issue by ryanwi** [emque/emque-consuming#44]
The auto-shutdown has worn out its welcome and it's now a good time to figure out the next approach to error handling. Going back to the original emque with retry and error queues seems like a place to start, just doing it safer so the retries don't pollute other consumer's queues.

Proposal

1) Consumers will create a retry and error queue for each queue they bind to a topic exchange. The error and retry queues will be direct queues used by the service only, not bound to an exchange.

2) RabbitMQ Messages should not fail to be acknowledged.

3) Emque Consuming applications should not shutdown by choice.

4) If an error is encountered during the processing of an emque message, emque consuming will enque the message into the retry queue and acknowledge the original RabbitMQ message. It can use the dead letter feature to give it a delay before processing.

5) The consumer can add an error count into the emque message and adjust the dead letter timeout based on number of errors (exponential back off).

6) After a certain number of errors, it can be moved into an error queue that has no processing associated with it.  Errors would need to be reviewed manually, or with some other application and determined if they should be purged or sent back to the queue.

**Comment by semmons99** [comment]
I really like this approach. The key will be making the extra queues, etc work without effort of the emque consuming developer. We need it to be "turn key retries."

**Comment by ryanwi** [comment]
In reviewing with @dmvt, changing the direction a bit.

These are the root of the current issues and we agree on this.
1) RabbitMQ Messages should not fail to be acknowledged.
2) Emque Consuming applications should not automatically shutdown

Specifics of error handling are desired to be
3) no retry queue

4) Known errors can be retried immediately
  - configurable by the application, allowed to specify which errors would be retried

5) Unknown errors will be acknowledged and put somewhere
  - by default into an error queue
    - for small numbers of errors, this is fine, but as the number of errors grows larger it becomes more difficult to review and replay or delete
    - Though the honeybadger error has the message details, we cannot necessarily grab this specific message out of the rabbit error queue easily.
  - configurable to specify redis or database, or someplace more conducive to reviewing the messages

**Comment by ryanwi** [comment]
Adding some refs for various handing of errors/retries, possibly with Rabbit's dead letter feature.

* http://www.pablocantero.com/blog/2014/11/29/sqs-to-the-rescue/#dead-letter-queues
* http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/SQSDeadLetterQueue.html
* https://www.rabbitmq.com/dlx.html
* http://rubybunny.info/articles/extensions.html#dead_letter_exchange_dlx
https://github.com/antirez/disque/blob/b5264359ddf0aa04a49b921c383c49ded7e7eea6/README.md#L63
*

**Comment by ryanwi** [comment]
One more reference

https://felipeelias.github.io/rabbitmq/2016/02/22/rabbitmq-exponential-backoff.html

**Comment by knappe** [comment]
Looking through solutions to https://en.wikipedia.org/wiki/Head-of-line_blocking that per message TTLs suffer as in https://felipeelias.github.io/rabbitmq/2016/02/22/rabbitmq-exponential-backoff.html's solution to introduce exponential backoff, we have a few solutions:

- A per queue TTL that each message is placed into based on their retry count
- Some convoluted exchange 
- Maybe another option?

I'm doing some research to see if there is a better way.

**Comment by knappe** [comment]
We added a config option to disable auto shutdown in 1.1.3.

https://github.com/emque/emque-consuming/pull/58

We're exploring auto retries in:

https://github.com/emque/emque-consuming/pull/55
